name:                                        SAP SID Infrastructure deployment

on:
  workflow_dispatch:
    inputs:
      sap_system:
        description:                         "SAP System configuration name, use the following syntax: ENV-LOCA-VNET-SID"
        required:                            true
        default:                             "TEST-WEEU-SAP05-X00"
        type:                                string
      workload_zone:
        description:                         "Workload Environment ...)"
        required:                            true
        type:                                environment
      test:
        description:                         "Test deployment without applying changes"
        type:                                boolean
        default:                             false

permissions:
  contents:                                  write
  id-token:                                  write
  issues:                                    write

env:
  TF_IN_AUTOMATION:                          true
  TF_LOG:                                    OFF
  ANSIBLE_CORE_VERSION:                      '2.16'
  TF_VERSION:                                '1.11.3'
  USE_MSI:                                   true

jobs:
  deploy_sap_infrastructure:
    name:                                    Deploy SAP Infrastructure
    environment:                             ${{ inputs.workload_zone }}
    runs-on:                                 self-hosted
    container:
      image:                                 ghcr.io/nnoaman/sap-automation:kimmos_playground

    steps:
      - name:                                Checkout the code
        uses:                                actions/checkout@v4
        with:
          fetch-depth:                       0

      - name:                                Get app token
        id:                                  get_workflow_token
        uses:                                peter-murray/workflow-application-token-action@v3
        with:
          application_id:                    "${{ secrets.APPLICATION_ID }}"
          application_private_key:           "${{ secrets.APPLICATION_PRIVATE_KEY }}"

      - name:                                Azure Login using Managed Identity
        uses:                                Azure/Login@v2
        with:
          auth-type:                         IDENTITY
          client-id:                         ${{ vars.MSI_ID }}
          tenant-id:                         ${{ vars.ARM_TENANT_ID }}
          subscription-id:                   ${{ vars.ARM_SUBSCRIPTION_ID }}

      - name:                                Configure Git Safe Directory
        run:                                 |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global --add safe.directory "/__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}"

      - name:                                Deploy SAP Infrastructure
        run:                                 |
          cd ${SAP_AUTOMATION_REPO_PATH}
          deploy/scripts/pipeline_scripts/v2/03-sap-system-deployment.sh
        env:
          APPLICATION_CONFIGURATION_NAME:    ${{ vars.APPLICATION_CONFIGURATION_NAME }}
          CONTROL_PLANE_NAME:                ${{ vars.CONTROL_PLANE_NAME }}
          APP_TOKEN:                         ${{ steps.get_workflow_token.outputs.token }}
          ARM_SUBSCRIPTION_ID:               ${{ vars.ARM_SUBSCRIPTION_ID }}
          TEST_ONLY:                         ${{ inputs.test }}
          SAP_SYSTEM_TFVARS_FILENAME:        ${{ inputs.sap_system }}.tfvars
          SAP_SYSTEM_FOLDERNAME:             ${{ inputs.sap_system }}
          USE_MSI:                           ${{ env.USE_MSI }}
